#! /usr/bin/env python3

import argparse
import base64
import configparser
import getpass
import hashlib
import os
import pathlib
import readline
import subprocess
import sys
import time


AVAILABLE_ENCODINGS = {"base32": base64.b32encode, "base64": base64.b64encode,
                       "base85": base64.b85encode,
                       "decimal": lambda b: str(int.from_bytes(b, endianness=PASSLE_ENDIANNESS)),
                       "hexadecimal": lambda b: base64.b16encode}
AVAILABLE_ENCODINGS_AS_STRING = ", ".join(AVAILABLE_ENCODINGS.keys())
DEFAULT_CLIPBOARD_TIMEOUT = 30
PASSLE = "PASSLE"
PASSLE_ENCODING = "encoding"
PASSLE_DEFAULT_ENCODING = "base64"
PASSLE_DEFAULT_HOME = os.path.join(pathlib.Path.home(), ".passle")
PASSLE_ENDIANNESS = 'big'
PASSLE_EXTENSION = ".pass"
PASSLE_HOME = "PASSLE_HOME"
PASSLE_KEY = "key"
PASSLE_LENGTH = "length"
PASSLE_SITES_DIRECTORY_NAME = "sites"
SCRYPT_MAX_LENGTH = 512
VERBOSITY = None

def printinfo(*args, **kwargs):
    print(*args, *kwargs, file=sys.stderr)

def derive_pass(master, key, encode=None, length=None):
    n = 16384 # n — CPU/memory cost factor
    r = 32 # r — block size
    p = 1 # p — paralellization factor
    maxmem = 128 * r * (n + p + 2)
    length = length or SCRYPT_MAX_LENGTH
    encode = encode or AVAILABLE_ENCODINGS[PASSLE_DEFAULT_ENCODING]
    result = hashlib.scrypt(master.encode('utf-8'),
                            salt=key.encode('utf-8'),
                            n=n, r=r, p=p, maxmem=maxmem,
                            dklen=SCRYPT_MAX_LENGTH)
    encoded_result = encode(result).decode('utf-8')
    if SCRYPT_MAX_LENGTH >= length:
        return encoded_result[:length]
    else:
        raise Exception("Password can't have length {}".format(length))


def store_directory(store_directory=None):
    store_directory = store_directory or os.environ.get(PASSLE_HOME) or PASSLE_DEFAULT_HOME
    return valid_store_directory(store_directory)


def valid_store_directory(prospective_dir, writable=False):
    if os.path.isfile(prospective_dir):
        raise FileExistsError("{0} is a file, not a directory".format(prospective_dir))
    elif not os.path.isdir(prospective_dir):
        os.makedirs(os.path.join(prospective_dir, PASSLE_SITES_DIRECTORY_NAME))
    # is directory, now check permissions
    if not os.access(prospective_dir, os.R_OK):
        raise PermissionError("Need read permission on {}".format(prospective_dir))
    if writable and not os.access(prospective_dir, os.W_OK):
        raise PermissionError("Need write permission on {}".format(prospective_dir))
    return prospective_dir


def list_site_files(store_dir):
    site_files_dir = os.path.join(store_dir, PASSLE_SITES_DIRECTORY_NAME)
    for root, _, files in os.walk(site_files_dir, topdown=True):
        for f in files:
            ext = os.path.splitext(f)[1]
            if ext == PASSLE_EXTENSION:
                yield (root, f)


def passle_ls(args):
    # FIXME: tree structure, have extension?
    store_dir = store_directory(args.store)
    for _, f in list_site_files(store_dir):
        print("- {}".format(f))


def find_site_file(name, store_dir):
    for d, f in list_site_files(store_dir):
        if os.path.splitext(f)[0] == name:
            return os.path.join(d, f)
    raise Exception("Could not find site file for {}".format(name))


def read_site_file(name, store_dir=None):
    # Site file is an INI-like configuration file as read by Python's
    # configparser module; it must have a PASSLE section with at least a key
    # named key and a corresponding value.
    store_dir = store_directory(store_dir)
    path = find_site_file(name, store_dir)
    if VERBOSITY:
        printinfo("Reading site file for {} at {}".format(name, path))
    config = configparser.ConfigParser()
    with open(path, 'r') as f:
        config.read_file(f)
    read_result = config.has_section(PASSLE) and config[PASSLE]
    if read_result:
        if VERBOSITY:
            printinfo("Read the following configuration:")
            printinfo(["{}: {}".format(k,v) for k,v in read_result.items()])
        return read_result
    else:
        raise Exception("Configuration must have a section named {}".format(PASSLE))


def passle_word(args):
    master = getpass.getpass(prompt="Master passphrase: ")
    length = args.length
    if args.as_key:
        read_result = {PASSLE_KEY: args.target}
    else:
        read_result = read_site_file(args.target, store_dir=args.store)
        length = length or read_result.getint(PASSLE_LENGTH)
    key = read_result.get(PASSLE_KEY)
    encode_name = args.encoding or read_result.get(PASSLE_ENCODING)
    encode = AVAILABLE_ENCODINGS.get(encode_name)
    if not encode:
        raise Exception("Could not find encoding for {}".format(encode_name))
    password = derive_pass(master, key, length=length, encode=encode)
    if not args.clip:
        print(password)
    else:
        clear = lambda: None
        # platform-dependent copy and clearing code
        if sys.platform == 'win32':
            raise NotImplementedError("Copy to and clear clipboard not implemented for Windows. Patches welcome")
        elif sys.platform == 'darwin':
            raise NotImplementedError("Copy to and clear clipboard not implemented for MacOSX. Patches welcome")
        else:
            clear = copy_nix(password)
        # clear clipboard after time
        try:
            time.sleep(args.clip or 30)
        finally:
            clear()
    return None


def validate(p, t, msg):
    if p(t):
        return t
    else:
        raise Exception(msg)


def passle_add(args):
    name = args.target
    if args.key:
        key = args.key
    else:
        key = name
    store_dir = store_directory(args.store)
    length = args.length or validate(int, input("Password length: "), "Password length must be integer")
    encoding_name = args.encoding or input("Password encoding: ").strip()
    encoding = validate(AVAILABLE_ENCODINGS.get, encoding_name, "Can't read password encoding {}, must be one of: {}".format(encoding_name, AVAILABLE_ENCODINGS_AS_STRING))
    site_info = {PASSLE_KEY : key,
                 PASSLE_LENGTH : length,
                 PASSLE_ENCODING : encoding}
    config = configparser.ConfigParser()
    config[PASSLE] = site_info
    config_fp = os.path.join(store_dir, PASSLE_SITES_DIRECTORY_NAME, name + PASSLE_EXTENSION)
    with open(config_fp, 'w') as configfile:
        config.write(configfile)
    if VERBOSITY:
        printinfo("Wrote password site information {} to {}".format(site_info, config_fp))
    return None

##
# copy-paste functionality
def copy_nix(string):
    _cmd = ["xclip", "-selection", "clipboard"]
    def clear_clipboard():
        subprocess.run(_cmd, check=True, input="".encode('ascii'))
        return None
    subprocess.run(_cmd, check=True, input=string.encode('utf-8'))
    return clear_clipboard



##
# CLI
parser = argparse.ArgumentParser(description="Hassle-free password-management.")
subparsers = parser.add_subparsers()
parser_word = subparsers.add_parser('word', help="Generate password")
parser_ls = subparsers.add_parser('ls', help="List available password sites")
parser_add = subparsers.add_parser('add', help="Add new password site")

def add_store_option(parser):
    parser.add_argument('-s', '--store', metavar="STORE_DIR",
                        help="path to password store directory (default: {})".format(PASSLE_DEFAULT_HOME))
    return None


def add_verbose_option(parser):
    parser.add_argument('-v', '--verbose', action='store_true')
    return None


def add_length_option(parser):
    parser.add_argument('-l', '--length', type=int,
                        metavar="PASSWORD_LENGTH",
                        help="length of password to produce (default depends on choice of encoding)")
    return None


def add_encoding_option(parser):
    parser.add_argument('-e', '--encoding', metavar="ENCODING",
                        choices=AVAILABLE_ENCODINGS.keys(),
                        default=PASSLE_DEFAULT_ENCODING,
                        help="Password encoding, one of: {} (default: {})".format(
                            AVAILABLE_ENCODINGS_AS_STRING, PASSLE_DEFAULT_ENCODING))
    return None


def add_target_argument(parser):
    parser.add_argument('target', metavar="TARGET",
                        help="target name to produce password to")
    return None

# word
add_store_option(parser_word)
add_verbose_option(parser_word)
parser_word.add_argument('-k', '--as-key', action='store_true',
                         help="treat TARGET as key, not as a site name")
parser_word.add_argument('-c', '--clip', nargs='?', type=int, metavar="TIMEOUT",
                         const=DEFAULT_CLIPBOARD_TIMEOUT,
                         help="""Copy password to clipboard instead of printing it.
Clear clipboard and return after TIMEOUT (default: {} seconds)""".format(DEFAULT_CLIPBOARD_TIMEOUT))
add_length_option(parser_word)
add_encoding_option(parser_word)
add_target_argument(parser_word)
parser_word.set_defaults(func=passle_word)


# add
add_store_option(parser_add)
add_verbose_option(parser_add)
parser_add.add_argument('-k', '--key',
                         help="if provided, use value as key and TARGET as alias, else TARGET is both")
add_length_option(parser_add)
add_encoding_option(parser_add)
add_target_argument(parser_add)
parser_add.set_defaults(func=passle_add)


# ls
add_store_option(parser_ls)
add_verbose_option(parser_ls)
parser_ls.set_defaults(func=passle_ls)


if __name__ == '__main__':
    if len(sys.argv) <= 1:
        parser.print_help(sys.stderr)
        sys.exit(1)
    args = parser.parse_args()
    VERBOSITY = args.verbose
    if VERBOSITY:
        printinfo("CLI options:", args)
    args.func(args)



# Local Variables:
# coding: utf-8-unix
# python-shell-interpreter: "python3"
# End:
